#!/bin/bash
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
# Copyright (c) 2014, Joyent, Inc.
#

set -x

if [[ ! -f /root/.ssh/authorized_keys ]]; then
    i=0
    while [ $i -le 3 ]; do
        sleep 3 

        authorized_keys=$(/lib/smartdc/mdata-get root_authorized_keys)

	echo "${authorized_keys}" | egrep -s "Error getting metadata"
	if [ $? -ne 0 ]; then
            mkdir -p /root/.ssh
            echo "${authorized_keys}" > /root/.ssh/authorized_keys
            chmod 700 /root/.ssh
            chmod 600 /root/.ssh/authorized_keys
            exit 0
	fi

        date >>/root/.ssh/debuglog 
        echo "debug: set-root-authorized-keys, failure or timeout...." \
            >> /root/.ssh/debuglog 
        ((i++))
    done
fi

exit 0
