.TH "sdc\-sbupload" "1" "June 2011" "" ""
.
.SH "NAME"
\fBsdc-sbupload\fR \-\- upload a service bundle
.
.SH "SYNOPSIS"
\fBsdc\-sbupload sbfilename\fR
.
.SH "DESCRIPTION"
This utility encrypts and uploads the given service bundle to the site
specified in the \fBsbapi_url\fR setting in the site's headnode configuration.

.SH "COPYRIGHT"
sdc\-sbupload Copyright (c) 2011 Joyent Inc\., All rights reserved\.
